config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get 'about', to: 'pages#about'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'

  resources :articles #, only: [:show, :index, :new, :create, :edit, :update, :destroy]
  get 'signup', to: 'users#new'
  #post 'users', to: 'users#create' 
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy' 

  resources :categories, except: [:destroy]
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    belongs_to :user
    has_many :article_categories
    has_many :categories, through: :article_categories
    validates :title, presence: true, length: {minimum: 6, maximum: 100}
    validates :description, presence: true, length: {minimum: 10, maximum: 300}
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
    belongs_to :article
    belongs_to :category 
end

app/models/category.rb
class Category < ApplicationRecord
    validates :name, presence: true, length: {minimum: 3, maximum: 25}
    validates_uniqueness_of :name
    has_many :article_categories
    has_many :articles, through: :article_categories
end

app/models/user.rb
class User < ApplicationRecord
    before_save { self.email = email.downcase }
    has_many :articles, dependent: :destroy
    validates :username, presence: true, 
                        uniqueness: { case_sensitive: false }, 
                        length: { minimum: 3, maximum: 25 } 
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, 
                      uniqueness: { case_sensitive: false }, 
                      length: { maximum: 105 },
                      format: { with: VALID_EMAIL_REGEX }
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user, :logged_in?

    def current_user
        if session[:user_id]
            @current_user ||= User.find(session[:user_id])
        end
    end

    def logged_in?
        !!current_user
    end

    def require_user
        if !logged_in?
            flash[:alert] = "You must be logged in to perform that action"
            redirect_to login_path
        end
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    
    before_action :set_article, only: [:edit, :update, :show, :destroy]
    before_action :require_same_user, except: [:index, :show]
    before_action :require_same_user, only: [:edit, :update, :destroy]
    #before_action :require_user, except: [:show, :index]

    def show
    end

    def index
        @articles = Article.paginate(page: params[:page], per_page: 1)
    end

    def new
        @article = Article.new
    end

    def edit
    end

    def create
        @article = Article.new(params.require(:article).permit(:title, :description))
        @article.user = current_user 
       if @article.save
            flash[:notice] = 'Article was created successfully'
            redirect_to article_path(@article)
       else
            render 'new' 
       end
    end

    def update

        if @article.update(params.require(:article).permit(:title, :description))
            flash[:notice] = 'Article was updated successfully'
            redirect_to @article
        else
            render 'edit'
        end
    end

    def destroy
        @article.destroy
        flash[:danger] = "Article was successfully deleted"
        redirect_to articles_path
    end

    private
        def set_article
            @article = Article.find(params[:id])  
        end
  
        def article_params
            params.require(:article).permit(:title, :description, category_ids: [])
        end
  
        def require_same_user
            if current_user != @article.user
                flash[:danger] = "You can only edit or delete your own articles"
                redirect_to root_path
            end
        end

        def require_same_user
            if current_user != @article.user && !current_user.admin?
                flash[:alert] = "You can only edit or delete your own articles"
                redirect_to @article
            end
        end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    before_action :require_admin, except: [:index, :show]
    def new
        @category = Category.new
    end

    def index
        @categories = Category.paginate(page: params[:page], per_page: 5)
    end

    def show
        @category = Category.find(params[:id])
    end

    def create
        @category = Category.new(category_params)
        if @category.save
            flash[:notice] = "Category was successfully created"
            redirect_to @category
        else
            render 'new'
        end
    end

    private
    def category_params
        params.require(:category).permit(:name)
    end

    def require_admin
        if !(logged_in? && current_user.admin?)
          flash[:alert] = "Only admins can perform that action"
          redirect_to categories_path
        end
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
        redirect_to  articles_path if logged_in?
    end

    def about
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new

    end

    def create
    
        user = User.find_by(email: params[:session][:email].downcase)
        if user && user.authenticate(params[:session][:password])
            session[:user_id] = user.id
            flash[:notice] = "Logged in successfully"
            redirect_to user
        else
            flash.now[:alert] = "There was something wrong with your login credentials"
            render 'new'
        end
    end

    def destroy
        session[:user_id] = nil
        flash[:notice] = "Logged out"
        redirect_to root_path
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    
    before_action :set_user, only: [:show, :edit, :update, :destroy]
    before_action :require_user, only: [:edit, :update]
    before_action :require_same_user, only: [:edit, :update, :destroy]
    def index
        @users = User.all
    end

    def show
       
        @articles = @user.articles
    end

    def new
        @user = User.new
    end

    def edit
       
    end

    def update
        
        if @user.update(user_params)
            flash[:notice] = "Your account information was successfully updated"
            redirect_to @user
        else
            render 'edit'
        end
        
    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            flash[:notice] = "welcome to Alpha blog, sign up sccessful"
            redirect_to articles_path
        else
            render 'new'
        end
    end

    def destroy
        @user.destroy
        if current_user.admin? 
            flash[:notice] = "Account and all asociated articles successfully deleted"
        else
            session[:user_id] = nil
        end
        redirect_to articles_path
    end

    private

    def user_params
        params.require(:user).permit(:username, :email, :password)
    end

    def set_user
        @user = User.find(params[:id])
    end

    def require_same_user
        if current_user != @user && !current_user.admin?
            flash[:alert] = "You can only edit or delete your own profile"
            redirect_to @user
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/sessions_helper.rb
module SessionsHelper

    # Logs in the given user.
    def log_in(user)
      session[:user_id] = user.id
    end
  
    # Returns the current logged-in user (if any).
    def current_user
      @current_user ||= User.find_by(id: session[:user_id])
    end
  
    # Returns true if the user is logged in, false otherwise.
    def logged_in?
      !current_user.nil?
    end
  end

app/views/articles/_article.html.erb
<% obj.each do |article| %>
    <div>
      <div>
        <div>
          <div>
              <%= link_to article.title, article_path(article) %>
          </div>
          <div >
            <%= truncate(article.description, length: 100) %>
            <div >
              <small>Created by: <%= article.user.username if article.user%>,
                      <%= time_ago_in_words(article.created_at) %> ago,
                      last updated: <%= time_ago_in_words(article.updated_at) %> ago</small>
            </div>
          </div>
            <div >
                <% if logged_in? && (article.user == current_user || current_user.admin?)  %>
                  <%= button_to "Edit", edit_article_path(article), method: :get %>
                  <%= button_to "Delete", article_path(article), method: :delete, 
                                            data: { confirm: "Are you sure you want to delete the article?"} %>  
                <% end %>
          </div>
      </div>
    </div>
  <% end %>

app/views/articles/edit.html.erb
<h1>Edit article</h1>
<%if @article.errors.any? %>
    <h3>The following errors prevented the article from being saved </h3>
    <ul>
        <% @article.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
    </ul>
<% end %>
<%= form_with(model: @article, local: true) do |f| %>
    <p>
        <%= f.label :title %><br/>
        <%= f.text_field :title %>
    </p>
   
    <p>
        <%= f.label :description %><br/>
        <%= f.text_area :description %>
    </p>
    
    <p>
        <%= f.submit %>
    </p>
<% end %>
<%= link_to 'Return to article listing', articles_path %>

app/views/articles/index.html.erb
<h1>Articles listing page</h1>
<%= will_paginate @articles %>
<br/>
<%= render 'article', obj: @articles %>
<br/>
<% if logged_in? %>
    <%= link_to 'Create new article', new_article_path %>
<% end %>

app/views/articles/new.html.erb
<h1>Create a new article</h1>
<%if @article.errors.any? %>
    <h3>The following errors prevented the article from being saved </h3>
    <ul>
        <% @article.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
    </ul>
<% end %>
<%= form_with scope: :article, url: articles_path, local: true do |f| %>
    <p>
        <%= f.label :title %><br/>
        <%= f.text_field :title %>
    </p>
   
    <p>
        <%= f.label :description %><br/>
        <%= f.text_area :description %>
    </p>
    
    <p>
        <%= f.submit %>
    </p>
<% end %>
<%= link_to 'Return to article listing', articles_path %>

app/views/articles/show.html.erb
<h1>Showing article details</h1>
<p><strong>Title: </strong><%= @article.title %></p>
<p><strong>Description: </strong><%= @article.description %></p>

<% if logged_in? && (@article.user == current_user || current_user.admin?) %>
    <%= link_to 'Edit', edit_article_path(@article) %> |
    <%= link_to 'Delete', article_path(@article), method: :delete, data: {confirm: "Are you sure?"} %> |
<% end %>
<%= link_to 'Return to article listing', articles_path %>

app/views/categories/index.html.erb
<h1>Articles All Categories</h1>
<div class="flickr_pagination">
  <%= will_paginate @categories, :container => false %>
</div>

<div class="container">
  <% @categories.each do |category| %>
    <div class="row justify-content-md-center">
      <div class="col-4 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-body">
            <h5 class="card-title"><%= link_to category.name, category_path(category), class: "text-success" %></h5>
          </div>
          <div class="card-footer text-muted">
            <small>Created <%= time_ago_in_words(category.created_at) %> ago, 
            edited <%= time_ago_in_words(category.updated_at) %> ago</small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/categories/new.html.erb
<h1 align="center">Create a new category</h1>

  <div >
    <%= render 'shared/errors', obj: @category %>
    <%= form_with(model: @category, role: "form", local: true) do |f| %>
      <div>
        <div>
          <%= f.label :name, "Category Name" %>
        </div>
        <div class="col-sm-8">
          <%= f.text_field :name, class: "form-control", placeholder: "Enter a name", autofocus: true %>
        </div>
      </div>
      <br/>
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <%= f.submit( class: 'btn btn-primary btn-lg') %>
        </div>
      </div>
    <% end %>
    <br/>
    <div class="col-xs-4 col-xs-offset-4">
      [ <%= link_to "Cancel request and return to articles listing", articles_path %> ]
    </div>
  </div>

app/views/categories/show.html.erb
<h1>Category: <%= @category.name %></h1>

app/views/layouts/_footer.html.erb
<div >
  <footer>
    <small>
    </small>
    <nav>
      <ul>
      <br/>
      <br/>
      <br/>
      <br/>
      <br/>
      <br/>
      <br/>
      <br/>
        <li><%= link_to "About", about_path %></li>
      </ul>
    </nav>
  </footer>
</div>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
    <% flash.each do |name, msg| %>
      <div class='alert alert-<%="#{name}" %>'>
        <a href="#" class="close" data-dismiss="alert">&#215;</a>
        <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav>
  <div>
    <div> 
      <ul>
          <li><%= link_to "Articles", articles_path %></li>
          <li><%= link_to "Users", users_path %></li>
          <li>
            <a href="#" >Actions <span></span></a>
              <% if logged_in? %>
              <ul>
                <li><%= link_to "New Article", new_article_path %></li>
              </ul>
             <% end %>
          </li>
      </ul>

      <% if logged_in? %>
        <li>
          <%= "(Admin)" if current_user.admin? %>
          <%= link_to current_user.username, user_path(current_user) %>
        </li>
          <li>
          <%= link_to 'Log out', logout_path %>
          </li>
          <li >
            <ul>
              <li><%= link_to "Edit your profile", edit_user_path(current_user) %></li>
              <li><%= link_to "View your profile", user_path(current_user) %></li>
              <li><%= button_to "Delete profile", user_path(current_user), method: :delete, data: { confirm: "Are you sure?" } %> </li>
            </ul>
          </li>
      <% else %>
          <li><%= link_to 'Log in', login_path %></li>
          <li><%= link_to 'Sign up', signup_path %></li>
      <% end %>
      <li>
      <a " href="#">
        Categories
      </a>
      </li> 
      <div>
        <li><% if logged_in? && current_user.admin? %>
          <%= link_to "Create new category", new_category_path, class: "dropdown-item" %>
        <% end %> </li> 
          <li><%= link_to "View categories", categories_path, class: "dropdown-item" %></li>
      </div>
   

    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AlphaBlog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/navigation' %>
  <%= render 'layouts/messages' %>
  <div class="container">
    <%= yield %>
  </div>
  <%= render 'layouts/footer' %>
  <% if false %>
    This code is for debugging purpose only
    <%= debug(params) if Rails.env.development? %>
  <% end %>
</body>
</html>

app/views/pages/about.html.erb
<h1>This is the about page of my blog app</h1>

<%= link_to "Home", root_path %>

app/views/pages/home.html.erb
<div>
  <h1>ALPHA BLOG</h1>
  <%= link_to "Sign up now", signup_path %>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="panel panel-danger">
        <div class="panel-heading">
          <h2 class="panel-title">
            <%= pluralize(obj.errors.count, "error") %>
            prohibited the <%= obj.class.name.downcase %> from being saved:
          </h2>
          <div class="panel-body">
            <ul>
              <% obj.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user %>

<div class='row'>
  <div class='col-xs-12'>
    <%= form_for(@user, :html => {class: "form-horizontal", role: "form"}) do |f| %>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :username %>
        </div>
        <div class="col-sm-8">
          <%= f.text_field :username, class: "form-control", placeholder: "Enter username", autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :email %>
        </div>
        <div class="col-sm-8">
          <%= f.email_field :email, class: "form-control", placeholder: "Enter email" %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :password %>
        </div>
        <div class="col-sm-8">
          <%= f.password_field :password, class: "form-control", placeholder: "Enter password" %>
        </div>
      </div>  
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <%= f.submit(@user.new_record? ? "Sign up" : "Update account", class: 'btn btn-primary btn-lg') %>
        </div>
      </div>
    <% end %>
    <div class="col-xs-4 col-xs-offset-4">
      [ <%= link_to "Cancel request and return to articles listing", articles_path %> ]
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<h1 align="center">Edit your profile</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1 align="center">All Alpha Bloggers</h1>
<div align="center">
  <% @users.each do |user| %>
    <ul>
    <div class="card-header font-italic">
    <%= link_to user.username, user %>
  </div>
      <div>
      <%= link_to "View profile", user %>
      <% if logged_in? %>
        <% if user == current_user %>
          <%= button_to "Edit profile", edit_user_path(user), method: :get%>
        <% end %>
        <% if current_user.admin? %>
        <%= button_to 'Delete', user_path(user), method: :delete %>
        <% end %>
      <% end %>
      </div>
    </ul>
  <% end %> 
</div>

app/views/users/new.html.erb
<h1 align="center">Sign up for Alpha Blog</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1 align="center"> <%= @user.username %>'s profile</h1>

<div>
    <% if logged_in? and @user == current_user %>
        <%= link_to "Edit your profile", edit_user_path(@user) %>
    <% end %>
</div>
<h3 align="center">Articles</h3>

<%= render 'articles/article', obj: @user.articles %>